version: '3.8'
services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./Dockerfile
    # volumes:
    #   - /home/isucon/webapp/tenant_db:/home/isucon/webapp/tenant_db