// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Occupations   string
	Positions     string
	Userlocations string
	Users         string
}{
	Occupations:   "occupations",
	Positions:     "positions",
	Userlocations: "userlocations",
	Users:         "users",
}
